workflows:
  flutter_build:
    name: Flutter Build
    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Install dependencies
        script: flutter pub get

      # - name: Run tests
      #   script: flutter test

      - name: Build Android APK
        script: flutter build apk

      - name: Build iOS IPA
        script: flutter build ios --no-codesign

    artifacts:
      - build/app/outputs/apk/release/app-release.apk
      - build/ios/ipa/Runner.ipa

    publishing:
      email:
        recipients:
          - alieid19961996@gmail.com
        notify:
          success: true 
          failure: true 
    
